# Generated by Django 5.1 on 2024-08-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(default=django.db.models.deletion.SET_NULL, null=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name='task',
            name='createed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
