# Generated by Django 5.1 on 2024-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_completed_at_alter_task_createed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
